name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Run unit tests with coverage
        run: |
          mkdir -p test-results coverage
          npm run test:ci -- --coverage --reporter=default --reporter=junit --outputFile=test-results/junit.xml | cat

      - name: Upload coverage report (LCOV)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-lcov
          path: coverage/lcov.info

      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html
          path: coverage

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-report
          path: test-results/junit.xml