name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta'

      - name: Ensure Docker is available
        run: docker --version

      - name: Provide env file for prod from secret
        shell: bash
        run: |
          mkdir -p envs
          if [[ -n "${{ secrets.PROD_ENV_FILE }}" ]]; then
            echo "Writing envs/prod.env from secret"
            printf "%s" "${{ secrets.PROD_ENV_FILE }}" > envs/prod.env
          elif [[ -n "${{ secrets.PRODUCTION_ENV }}" ]]; then
            echo "Writing envs/prod.env from legacy secret"
            printf "%s" "${{ secrets.PRODUCTION_ENV }}" > envs/prod.env
          else
            echo "Error: PROD_ENV_FILE secret not set" >&2
            exit 1
          fi
          echo "Prod env keys:"; cut -d= -f1 envs/prod.env | sed 's/.*/  - &/'

      - name: Build and Push Image
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh prod 